apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tempweb
  template:
    metadata:
      labels:
        app: tempweb
    spec: 
      containers:
        - name: tempweb
          image: debux/conversao-temperatura:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tempweb
spec:
  selector:
    app: tempweb
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 30000
  type: NodePort